## ====================================================================================== ##
# Title:    Associating edX Learner Performance and Interactions to Learning Objectives
# Project:  edX Learning Objective Visual Analytics WOrkflow
#
#     Copyright 2019-2020 Michael Ginda
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#     
#     http://www.apache.org/licenses/LICENSE-2.0
#     
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#
# Authors:      Michael Ginda
# Affiliation:  Indiana University
# 
# Description: This R script associates student grade performance data and 
#              processed student content interactions (event logs) with learning  
#              objectives that were coded to an edx courses' organizational and 
#              content structure to create student analytics of student interaction 
#              (dwell times & event counts) and grade performance towards a course's
#              learning objectives.
#
# File input stack: 
#            1) A processed edX Course structure and content module list
#               and learning objective codes:
#               - Data is a modified version of edX course structure generated by
#                 edX-1-courseStructureMeta.R, which is apart of the edX Learner and 
#                 Course Analytics and Visualization Pipeline,
#                 see: https://github.com/cns-iu/edx-learnertrajectorynetpipeline;
#               - Filename: {org}+{course}+{term}-learningObjective-analysis.csv;
#               - See sample: dataB.csv
#            2) A list of student userIDs from an edX course:
#               - Data is a processing results of script edX-4-eventLogFormatter.R, which
#                 is apart of the edX Learner and Course Analytics and Visualization Pipeline;
#               - Note, any list of students' user identifiers with processed event
#                 logs may be used in this script;
#               - Filename: {org}+{course}+{term}-user-students-active.csv;
#               - See sample: dataC.csv
#            3) A collection of student's edx course subsection grades.
#               - Data come from course's edX Data Package; 
#               - Filename: grades_persistentsubsectiongrade.csv;
#               - See sample: dataD.csv
#            4) A "studentevents_processed" directory containing one or more processed  
#               student event log CSV file(s):
#               - Data are processing results of scripts edX-3-eventLogExtractor.R &
#                 edX-4-eventLogFormatter.R, which are apart of the edX Learner and 
#                 Course Analytics and Visualization Pipeline;
#               - Filenames: /studentevents_processed/{user_id}.csv;
#               - See sample: dataE.zip
#
# Output files:                        
#            1) A data table of learning object grade and activity calculations for each 
#               student:
#               - Used in script: edX-learningObjective-2-gradeTime-boxplots.R
#               - Filename: {org}+{course}+{term}-learningObjectve-studentAnalysis.csv;
#               - See sample: dataF.csv
#
# Package dependencies: tclick, tidyr, magrittr, reshape2, plyr, dplyr, stringr
#
# Change log:
# 05.2019 - Initial code creating learning objective grade and time analysis &
#           box-plot and parallel coordinate chart visualiations.
# 12.2019 - Updated script to clarify data sets used; re-order arguments for consistency; 
#           clarified inline documentation;
# 01.2020 - Update script header, paths, data load, exported file names
# 04.2020 - Clean up script for sharing publically, adding inline notes for users.
#
## ====================================================================================== ##

#### Environmental Setup ####
rm(list=ls()) 

# Load required packages
require(tcltk)      # for setting paths
require(tidyr)      # for replacing NAs
require(magrittr)   # for data piping
require(reshape2)   # for data reshaping
require(plyr)       # for data aggregations
require(dplyr)      # for data manipulations
require(stringr)    # for string parsing

# Set Paths
# Checks if a user has previously assign a path with a prior script.
# If false, user should assign path to the edx Data Package 
# "state" directory for the course being studied.
if(exists("path_data")==FALSE){
  path_data = tclvalue(tkchooseDirectory())
}

# Checks if a user has previously assign a path with a prior script.
# If false, user assigns path to a directory of processing results
# generated by the EdX Learner and Course Analytics and Visualization 
# Pipeline for the course being studied. This directory will be used to 
# save processing results created by this script.
if(exists("path_output")==FALSE){
  path_output = tclvalue(tkchooseDirectory())
}

#### Load Data ####
# Course Module Learning Objective Coding Results
# Learning objectives are applied to each module (content) using the
# course structure generated by script edX-1-courseStructureMeta.R from
# the EdX Learner and Course Analytics and Visualization Pipeline,
# see: https://github.com/cns-iu/edx-learnertrajectorynetpipeline.
# User should update the "pattern" parameter with naming convention the 
# learning objective analysis that they have completed for a given course.
lo <- read.csv(file=list.files(full.names = TRUE, recursive = FALSE, 
                               path = paste0(path_output,"/analysis/"),
                               pattern = "LearningObjectives-analysis.csv$"), header=T)

# A list of edx student identifiers. The list of identifiers used by this 
# analysis was generated by script edX-4-eventLogFormatter.R, which is 
# apart of the EdX Learner and Course Analytics and Visualization Pipeline,
# see: https://github.com/cns-iu/edx-learnertrajectorynetpipeline.
# User lists generated by the pipeline are saved in results output directory
# of user identifier lists.
users <- read.csv(file=list.files(full.names = TRUE, recursive = FALSE, 
                                  path = paste0(path_output,"/userlists/"),
                                  pattern = "user-students-active.csv$"), header=T)[c(1)]
names(users) <- "user_id"

# Student course subsection grades - measured at the sequential level
# of course structure. Sequential module identifiers are captured in the
# processed EdX course structure for content modules, and should be kept in a
# subsequent learning objective analysis.
subGrades <- read.csv(file=list.files(full.names = TRUE, recursive = FALSE, 
                                      path = paste0(path_data,"/state/"),
                                      pattern = "grades_persistentsubsectiongrade.csv$"), 
                                      header=T)[c(2:7)]

# Event log file paths 
# These data were generated by script edX-4-eventLogFormatter.R, which is 
# apart of the EdX Learner and Course Analytics and Visualization Pipeline,
# see: https://github.com/cns-iu/edx-learnertrajectorynetpipeline.
filePaths <- paste0(path_output,"/studentevents_processed/",users$user_id,".csv")

#### Data Processing ####
# Save the time (to compute elapsed time of script)
start <-  proc.time() 

# Course Identifier for exported files
course_id <- gsub("\\/","\\-",lo[1,]$courseID)

### Preparing Learning Objectives Data
# Reshape Learning Objective matrix to a list, NAs removed from data set (hidden modules or instructions for course)
lo <- lo %>% melt(id.vars=c(1:11),variable.name="objective",na.rm=T)
# Updates objective factors
lo$objective <- sub("[.]{1}", " ", lo$objective)

## Setting Learning Objective Identifiers
lo_id <- as.data.frame(unique(lo$objective))
names(lo_id) <- "objective"

## Mapping Learning Objectives to Sequential Modules
# Subset to only values 1, indicating a learning objective was observed, and tree levels of 2 (sequential modules), 
# then refactor identifiers
lo_s <- lo[lo$value==1 & lo$treelevel==2,c("mod_id","mod_type","objective")] %>% 
  mutate(mod_id = factor(mod_id)) %>% mutate(mod_type = factor(mod_type))

## Mapping Learning Objectives to Content Modules
# Subset to only values 1, indicating a learning objective was observed, and tree levels of 4 (content modules), 
# then refactor identifiers
lo_c <- lo[lo$value==1 & lo$treelevel==4,c("mod_id","mod_type","seqModPar","objective")] %>% 
  mutate(mod_id = factor(mod_id)) %>% mutate(mod_type = factor(mod_type))

#### Learning Objective Grades ####
# Preparing Sequential Module Grade Data (edX persistent subsection grades)
subGrades <- subGrades[,c("usage_key","earned_graded","possible_graded","user_id")] %>% 
  mutate(mod_id = stringr::str_split_fixed(usage_key, "\\@", 3)[,3])

# Some sequential modules are removed if they are not mapped to learning objectives (e.g. prequestionnaires, hidden content, etc.)
grade <- join(subGrades[,c("mod_id","earned_graded","possible_graded","user_id")],
              lo_s[,c("mod_id","objective")],by="mod_id",type = "left") %>% 
  na.exclude() %>%  
  ddply(.,~ objective+user_id, summarise,
        earned_points = sum(earned_graded),
        possible_points = sum(possible_graded),
        per_earned =round(sum(earned_graded,na.rm=T)/sum(possible_graded,na.rm=T)*100,3))
grade <- grade[grade$user_id %in% users$user_id,]

#### Learning Objective Dwell Times and Event Counts ####
#Create a shell data.frame
active  <- data.frame(objective=as.character(),                     # Learning Objective
                      dwell=as.numeric(),                           # Dwell Time (Min)
                      events=as.numeric(),                          # Event Count
                      created=as.POSIXct(as.character()),           # First Event Log Created
                      modified=as.POSIXct(as.character()),          # Last Modification to Event Log
                      user_id=as.integer(),                         # Student Identifier
                      stringsAsFactors=FALSE)

## Converting Student Event Logs to create Learning Objectives Transition Networks 
# Loop individual student logs to create an edge list of transitions between learning objectives
for(i in 1:length(filePaths)){
  message("Processing log file ", i, " of ", length(filePaths))
  print(proc.time() - start)
  # Load data set
  data <- read.csv(filePaths[i])[,c("course_id","user_id","mod_hex_id","time","period",
                                    "attempts","grade","max_grade","success")]
  # Renames field to join with Learning Objectives 
  names(data)[3] <- "mod_id"
  
  #Updates Time field to R compliant format
  data$time  <- as.POSIXct(data$time,origin="1970-01-01") 
  
  # Left join learning objectives for content modules (lo_c) to student log (data)
  data <- join(as.data.frame(data),as.data.frame(lo_c[,c("mod_id","objective")]),by="mod_id")
  
  # Remove all events that are not associated with an objective
  data <- data[!is.na(data$objective),]
  
  # Learning Objective Dwell Time and Event Count Calculations
  #Checks if students have interacted with modules connected with LO 
  if(nrow(data)>0){
    tmp <- data %>% ddply(.,~objective,summarise,
                          events = length(period),
                          dwell = sum(period),
                          create = min(time),
                          modified = max(time),
                          user_id = unique(user_id)) %>% 
      join(lo_id,.,by="objective") %>%
      replace_na(list(dwell=0,
                      events=0,
                      user_id=unique(data$user_id))) 
  }
  active <- rbind(active,tmp)
}

#Combine learning objective grade and activity analysis
stdLOstats <- join(grade,active, by=c("objective","user_id"))

#Transfrom LO labels to groups and sub-objectives
stdLOstats <- stdLOstats %>% 
  mutate(group = str_split(objective, "\\.")) %>% 
  rowwise() %>% 
  mutate(group = group[1]) %>%
  mutate(objective = str_split(objective, " ")) %>% 
  rowwise() %>% 
  mutate(objective = objective[2])
#Update field data types
stdLOstats$group <- factor(stdLOstats$group)
stdLOstats$objective <- factor(stdLOstats$objective)
stdLOstats <- stdLOstats[,c(10,1:2,8:9,3:7)]

### Saves data used for Box Plots
write.csv(stdLOstats , file=paste0(path_output,"/analysis/",course_id,"-LearningObjectives-studentAnalysis.csv"), 
          row.names=F) 

# Clean up environment
rm(lo,users,filePaths,subGrades,
   grade,active,lo_id,lo_c,lo_s,
   data,i,tmp)

#### Finishing Details ####
#Indicate completion
message("\n**** Complete! ****\n")
## Script processing time feedback
#print the amount of time the script required
cat("\n\n\nComplete script processing time details (in min):\n")
print((proc.time()[3] - start[3])/60)