## ====================================================================================== ##
# Title:   Visualization of student performance and activity across learning objective
#          for edX courses
# Project: edX Learning Objective Visual Analytics Workflow
# 
#     Copyright 2019-2020 Michael Ginda
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#     
#     http://www.apache.org/licenses/LICENSE-2.0
#     
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#
# Authors:      Michael Ginda
# Affiliation:  Indiana University
# 
# Description: This R script creates boxplot visualizations of student grade performance 
#              and activity data across learning objectives associated with an edX course.
#
# File input stack: 
#            1) A processed edX Course structure and content module list
#               and learning objective codes:
#               - Data is a modified version of edX course structure generated by
#                 edX-1-courseStructureMeta.R, which is apart of the edX Learner and 
#                 Course Analytics and Visualization Pipeline,
#                 see: https://github.com/cns-iu/edx-learnertrajectorynetpipeline;
#               - Filename: {org}+{course}+{term}-learningObjective-analysis.csv;
#               - see sample dataB.csv
#            2) A data table of learning object grade calculations for each student:
#               - Data created by edX-learningObjective-1-dataProcessing.R, from 
#                 edX Learner Objective Grade and Activity Visual Analytics project;
#               - Filename: {org}+{course}+{term}-learningObjectve-studentAnalysis.csv;
#               - See sample dataF.csv
#
# Output files:                        
#            1) A TIFF formatted visualization of boxplots of
#               student dwell times across course learning objectives:
#               - {org}+{course}+{term}-boxplots-lo-dwelltime.tiff
#            2) A TIFF formatted visualization of boxplots of
#               student grade performance across course learning objectives:
#               - {org}+{course}+{term}-boxplots-lo-grades.tiff
#
# Package dependencies: tcltk, reshape2, ggplot2, colorspace, qualpalr
#
# Change log:
# 05.2019 - Initial code creating learning objective grade and time analysis &
#           box-plot and parallel coordinate chart visualiations.
# 12.2019 - Updated script to clarify data sets used; re-order arguments for consistency; 
#           clarified inline documentation; generalized script for any edX course; split
#           out visualizations into a separate script.
# 04.2020 - Revise code for publication and sharing.
#
## ====================================================================================== ##
#### Environmental Setup ####
# Load required packages
require(tcltk)      # for setting paths
require(reshape2)   # for reshaping data
require(ggplot2)    # for boxplot visualization
require(colorspace) # for color palette generation
require(qualpalr)   # for qualitiative color palette generation

# Set Paths 
# Set path to edX course analysis output directory.
# Checks if a user has previously assign a path with a prior script
# If false, user assigns path to a directory of processing results
# generated by the EdX Learner and Course Analytics and Visualization 
# Pipeline for the course being studied. This directory will be used to 
# save processing results created by this script.
if(exists("path_output")==FALSE){
  path_output = tclvalue(tkchooseDirectory())
}

#### Load Data ####
#Note, file paths may need to be adjusted prior to use of this script.
# Read in course identifier from learning objective analysis
course_id <- read.csv(file=list.files(full.names = TRUE, recursive = FALSE, 
                               path = paste0(path_output,"/analysis/"),
                               pattern = "LearningObjectives-analysis.csv$"), header=T)[1,3]

# Student learning objective grades data
stdLOstats <- read.csv(file=list.files(full.names = TRUE, recursive = FALSE, 
                                      path = paste0(path_output,"/analysis/"),
                                      pattern = "LearningObjectives-studentAnalysis.csv$"), header=T)

#### Data Preparation ####
# Ensures that learning objective field is a factor
stdLOstats$objective <- as.factor(stdLOstats$objective)

#### Visualization ####
# Set basic ggplot2 theme
theme_set(theme_light())

# Color Palette
pal <- qualpal(n = 5, colorspace = list(h=c(-7,223),s=c(.2,.91),l=c(.5,.83)), 
               cvd = "protan", cvd_severity = 0)

## Box plots for LO distributions
# Note, user may want to adjust paths used to save output visualizations for figures produced by these scripts.

# Total Dwell Time (Duration)
tiff(filename=paste0(path_output,"/analysis/",course_id,"-boxplots-lo-dwelltime.tiff"),
    width = 13, height = 7, units = "in", res=300)

ggplot(data=stdLOstats,
       aes(objective, dwell)) +
  geom_boxplot(aes(fill=group)) +
  scale_fill_manual(values=pal$hex) +
  ylim(0,1000) + 
  xlab("Learning Objectives") + ylab("Total Duration (Min.)") +
  guides(fill=guide_legend(title = "Learning Objective Group")) + theme(legend.position="bottom") +
  theme(
    #X Axis
    axis.title.x = element_text(colour="grey20",
                                margin=unit(c(3,0,0,0),"mm"),
                                size=14),
    axis.ticks.x.bottom = element_line(colour="grey60", linetype = "solid"),
    axis.line.x = element_line(color="grey60", linetype = "solid", size = .75),
    axis.text.x = element_text(colour="grey20",
                               size=12),
    #Y Axis
    axis.title.y = element_text(colour="grey20", 
                                margin=unit(c(0,3,0,0),"mm"),
                                size=14),
    axis.line.y = element_blank(),
    axis.ticks.y = element_line(colour="grey90", linetype = "solid"),
    axis.text.y = element_text(colour="grey20",
                               size=12),
    #Legend
    legend.title = element_text(colour="grey20",
                                size=14),
    legend.text = element_text(colour="grey20",
                               size=12),
    legend.position = "bottom",
    legend.margin = margin(2,0,2,0, unit = "mm"),
    legend.justification = "left",
    
    #Panel
    panel.border = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_line(colour="grey90", linetype = "solid"),
    panel.grid.minor.y = element_blank()
  )
dev.off()

## Percent Grade Earned 
tiff(filename=paste0(path_output,"/analysis/",course_id,"-boxplots-lo-grades.tiff"),
     width = 13, height = 7, units = "in", res=300)
ggplot(data=stdLOstats,
       aes(objective,per_earned)) +
  geom_hline(yintercept=60, color="dark red", linetype = 3, size = 1) +
  geom_boxplot(aes(fill=group)) +
  scale_fill_manual(values=pal$hex) +
  ylim(0,101) +
  xlab("Learning Objectives") + ylab("Grades (Percentage)") +
  guides(fill=guide_legend(title = "Learning Objective Group")) +
  theme(#X Axis
    axis.title.x = element_text(colour="grey20",
                                margin=unit(c(3,0,0,0),"mm"),
                                size=14),
    axis.ticks.x.bottom = element_line(colour="grey60", linetype = "solid"),
    axis.line.x = element_line(color="grey60", linetype = "solid", size = .75),
    axis.text.x = element_text(colour="grey20",
                               size=12),
    #Y Axis
    axis.title.y = element_text(colour="grey20", 
                                margin=unit(c(0,3,0,0),"mm"),
                                size=14),
    axis.line.y = element_blank(),
    axis.ticks.y = element_line(colour="grey90", linetype = "solid"),
    axis.text.y = element_text(colour="grey20",
                               size=12),
    #Legend
    legend.title = element_text(colour="grey20",
                                size=14),
    legend.text = element_text(colour="grey20",
                               size=12),
    legend.position = "bottom",
    legend.margin = margin(2,0,2,0, unit = "mm"),
    legend.justification = "left",
    #Panel
    panel.border = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_line(colour="grey90", linetype = "solid"),
    panel.grid.minor.y = element_blank()
  )

dev.off()

#### Finishing Details ####
#Indicate completion
message("\n**** Complete! ****\n")
## Script processing time feedback
#print the amount of time the script required
cat("\n\n\nComplete script processing time details (in sec):\n")
print((proc.time()[3] - start[3])/60)
## Clear environment variables
rm(list=ls())