## ====================================================================================== ##
# Title:   edX Chapter module to Learning Objective Bipartite Network 
# Project: edX Learning Objective Visual Analytics
# 
#     Copyright 2020 Michael Ginda
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#     
#     http://www.apache.org/licenses/LICENSE-2.0
#     
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#
# Authors:      Michael Ginda
# Affiliation:  Indiana University
# 
# Description: This R script creates a bipartite network between chapter modules and 
#              learning objective for an edX course, specifically, a node and
#              edge list that may be used in secondary analytics tools, such as Gephi.
#              The script also exports a color palette set of web color hexadecimal 
#              codes used in the final visualization of this network.
#
# File input stack: 
#            1) A processed edX Course structure and content module list
#               and learning objective codes:
#               - Data is a modified version of edX course structure generated by
#                 edX-1-courseStructureMeta.R, which is apart of the edX Learner and 
#                 Course Analytics and Visualization Pipeline,
#                 see: https://github.com/cns-iu/edx-learnertrajectorynetpipeline;
#               - Filename: {org}+{course}+{term}-learningObjective-analysis.csv;
#               - see sample dataB.csv
#
# Output files:                        
#            1) A node list used for network analysis and visualization, exported as a
#               CSV file:
#               - {org}+{course}+{term}-ChpMod2LONet-nodes.csv
#            2) An edge list used for network analysis and visualization, exported as a
#               CSV file:
#               - {org}+{course}+{term}-ChpMod2LONet-edges.csv
#            3) An set of hexadecimal color codes associated with node groups, 
#               exported as a
#               CSV file:
#               - {org}+{course}+{term}-ChpMod2LONet-palette.csv
#
# Package dependencies: tcltk, reshape, plyr, dplyr, magrittr, colorspace, qualpalr
#
# Change log:
# 04.2020 - Initial code creating chapter module to learning objective network data set.
#
## ====================================================================================== ##
#### Environmental Setup ####
# Load required packages
require(tcltk)      # for setting paths
require(reshape2)   # for reshaping data
require(plyr)       # for data aggregations
require(dplyr)      # for data manipulations
require(stringr)    # for string manipulation
require(magrittr)   # for data piping
require(colorspace) # for color palette generation
require(qualpalr)   # for qualitiative color palette generation

# Set Paths 
# Set path to edX course analysis output directory.
# Checks if a user has previously assign a path with a prior script
# If false, user assigns path to a directory of processing results
# generated by the EdX Learner and Course Analytics and Visualization 
# Pipeline for the course being studied. This directory will be used to 
# save processing results created by this script.
if(exists("path_output")==FALSE){
  path_output = tclvalue(tkchooseDirectory())
}

#### Load Data ####
# Note, file paths may need to be adjusted prior to use of this script.
# Read in course identifier from learning objective analysis
course_id <- read.csv(file=list.files(full.names = TRUE, recursive = FALSE, 
                               path = paste0(path_output,"/analysis/"),
                               pattern = "LearningObjectives-analysis.csv$"), header=T)[1,3]

# Course structure with learning objective codes
data <- read.csv(file=list.files(full.names = TRUE, recursive = FALSE, 
                                       path = paste0(path_output,"/analysis/"),
                                       pattern = "LearningObjectives-analysis.csv$"), 
                 header=T, stringsAsFactors = F)

#### Data Preparation ####
# Select module type, module name, and learning objective codes from data set
data <- data[,c(5,4,6,12:ncol(data))]

# Select chapter modules and melt data frame to identify 
data <- data[data$mod_type=="chapter",] %>% melt(id.vars=c(1:3),variable.name="objective",na.rm=T)

# Keep only relationships that have a positive association between chapter modules 
# and learning objectives
data <- data[data$value==1,]

# Creates the dataframe of chapter nodes
chps <- as.data.frame(unique(data[,c(1,3)]))
chps <- chps %>% 
  arrange(order) %>%
  mutate(group="Chapter", x=0, y=1:nrow(chps))
chps <- chps[,-c(2)]

# Clean up Learning Objective Identifiers names
data$objective <- sub("[.]{1}", " ", data$objective)

# Creates a dataframe of learning objective nodes
los <- as.data.frame(unique(data$objective),stringsAsFactors=F)
names(los) <- "name"
los <- los %>% mutate(group=str_split(name, "\\.")) %>% 
  rowwise() %>% 
  mutate(group = group[1])
los$x = 100
los$y <- 1:nrow(los) 

# Creates node list by combine chps and los dataframe
nodes <- rbind(chps,los)
# Add a node ID field
nodes$id <- 1:nrow(nodes)
# Remove data frames
rm(chps,los)

# Update data to an edge list
# where Chapter are source and learning objectives are targets 
# First join node list "name" and "id" to data
data <- join(data,nodes[,c("name","id")],by="name")
# Next, remove name, module type, and order fields from data
data <- data[,-c(1:3)]
# Then, rename objective field to "name", 
# keep value field, and rename "id" to source
names(data) <- c("name","value","source")
# Next, repeat join node list "name", "id", and "group" fields
# with the new "name" field of learning objectives
data <- join(data, nodes[,c("name","id","group")],by="name")
# Rearrange data columns, and drop "name" field
data <- data[,c(3,4,2,5)]
names(data)[2] <- "target"

# Clean up nodes data frame by updating 
# Rearrange data frame columns, and rename name field to label
nodes <- nodes %>% 
  select(id, everything()) %>% 
  rename("label" = "name")
nodes$label <- gsub("LO ","", nodes$label)

#### Network pallet information ####
# Export Learning Objective Color Palette Set used in figures.
# Note the number of palette colors generated is manually set to match
# Figures 1 and 2 from script edX-learningObjective-2-gradeTime-boxplots.R
# Additionally, the chapter color is set manually.
pal <- qualpal(n = 5, colorspace = list(h=c(-7,223),s=c(.2,.91),l=c(.5,.83)), 
               cvd = "protan", cvd_severity = 0)
pal <- as.data.frame(pal$hex, stringsAsFactors=F)
pal$label <- unique(nodes[nodes$group!="Chapter",]$group)
pal <- rbind(pal,c("#efa8d7","Chapter"))
names(pal) <- c("hex_code","group")

#### Exporting processing results ####
write.csv(data, file=paste0(path_output,"/analysis/",course_id,"-ChpMod2LONet-edges.csv"), 
          row.names=F) 
write.csv(nodes, file=paste0(path_output,"/analysis/",course_id,"-ChpMod2LONet-nodes.csv"), 
          row.names=F) 
write.csv(pal, file=paste0(path_output,"/analysis/",course_id,"-ChpMod2LONet-palette.csv"), 
          row.names=F) 

#### Finishing Details ####
## Clear environment variables
rm(list=ls())