---
title: "Data Processing"
author: "Michael Ginda"
date: "January 24, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Environment Set-Up

```{r env include=FALSE}
# Clearn up environment
rm(list=ls()) 

# Load required packages
require(RCurl)    #Loading data from web
library(magrittr)   # for piping
library(plyr)       # for data aggregations
library(dplyr)      # for filtering
library(reshape2)   # for data reshaping
library(igraph)     # for creating an adjacency matrix
```

## Path to Data

```{r path, eval=FALSE, echo=T}
#Path to edX data package
# Assigns a path to directory with original edX course data files used in data processing
path_data <- "Y:/PROJECT/EDX_DATA/COURSEID/state/"

# Assigns a path to directories with results of the edX Learner and Course Analytics and Visualization Pipeline scripts
path_results <- "Y:/PROJECT/RESULTS/studentevents_processed/"
```

## Load Data
```{r data}
# Learning Objective Analysis of Course Modules
lo <- read.csv(text=getURL("https://raw.githubusercontent.com/mginda/edx-learningObjective-trajectorynetwork/master/data/dataB.csv",ssl.verifypeer = FALSE), header=T)

#Alternative load in your own learning objective analysis of course structure
#lo <- read.csv(file=paste0(path_results,"/learningObjectives/","LEARNING_OBJECTIVE_ANALYSIS.csv")

# Student course subsection grades - measured at the sequencial group level of course structure
subGrades <- read.csv(text=getURL("https://raw.githubusercontent.com/mginda/edx-learningObjective-trajectorynetwork/master/data/dataD.csv", ssl.verifypeer = FALSE), header=T)[2:7]

#Alternative load in your own subsection grades
#subGrades <- read.csv(file=paste0(path_data,"/state/","grades_persistentsubsectiongrade.csv")

# Create paths to student logs data
# Load list of users to create list of log file paths
users <- read.csv(text=getURL("https://raw.githubusercontent.com/mginda/edx-learningObjective-trajectorynetwork/master/data/dataC.csv", ssl.verifypeer = FALSE), header=T)

#Alternative load in your own user list
#users <- read.csv(file=paste0(path_data,"/state/","certificates.csv")
```

###Event Log Filepaths
```{r file, eval=FALSE, echo=T}
filePaths <- paste0(path_data,"/",users$user_id,".csv")
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
